### PR TITLE
Add “where:” option for upsert_keys

### PR DESCRIPTION
**Pull request by danielcooper**
Adds a `:where` keyword argument for the `upsert_keys` configuration.

### CODE REVIEW

**Review by me — APPROVED** [review]
Looks good to me 👍 
I think it makes sense to use a SQL string rather than Arel here, since it's a static condition.

**Comment by pedrocunha** [comment]
This looks good, but could we attempt to see if the author of the gem would accept these changes first? Would be nice that we are in sync with upstream

**Comment by me** [comment]
Yeah there's already a PR here https://github.com/jesjos/active_record_upsert/pull/60

**Comment by jphastings** [comment]
The upstream PR got merged :)

**Pull request closed without merging**
